import = ["~/.config/alacritty/themes/noctalia.toml"]

[scrolling]
multiplier = 15

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\x1b\r"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh://|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Control"
