import = ["~/.config/alacritty/themes/noctalia.toml"]

[scrolling]
multiplier = 5

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\x1b\r"
