[niri]
input_path = "~/.config/noctalia/templates/niri-colors.kdl"
output_path = "~/.config/niri/colors.kdl"
post_hook = "niri msg action load-config-file"

[alacritty]
input_path = "~/.config/noctalia/templates/alacritty-colors.toml"
output_path = "~/.config/alacritty/colors.toml"
