[config]

[templates.nvim]
input_path = "~/.config/noctalia/templates/nvim-colors.lua"
output_path = "~/.config/nvim/lua/noctalia_colors.lua"
post_hook = "pkill -SIGUSR1 nvim"

[templates.tmux]
input_path = "~/.config/noctalia/templates/tmux-colors.conf"
output_path = "~/.config/tmux/colors.conf"
post_hook = "tmux source-file ~/.config/tmux/tmux.conf"

[templates.walker]
input_path = "~/.config/noctalia/templates/walker-style.css"
output_path = "~/.config/walker/themes/noctalia/style.css"

