theme = "noctalia"
force_keyboard_focus = true
close_when_open = true
click_to_close = true
hide_quick_activation = true
hide_action_hints = true

[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[providers]
default = ["desktopapplications"]
empty = ["desktopapplications"]

[keybinds]
close = ["Escape"]
